---
title: "pars_125000"
author: "Al Irvine and Simon Norris"
date: "April 5, 2020"
output: html_document
---

```{r setup, include = TRUE, echo =FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, 
                      fig.align="center", fig.width = 5.118, fig.height = 3.409,
                      fig.path = ('fig/'))
```


```{r include = FALSE, echo =TRUE, message=FALSE}

plot <- drake::r_vis_drake_graph(main = 'Interactive Drake Workflow Graph Showing Project Structure and Dependencies')
```

 
I believe this reads the _drake.R file in the main project directory
```{r}
plot
```

Set up for the leaflet map with tracks and track points loaded within the same chunk.  All the packages, functions and plan for data targets is detailed in our .R/ folder.
```{r echo=TRUE}
loadd(tracks)
loadd(track_points)


my_site <- '125000'


##doll up the gpx data
##here are the indexes of the points
track_point_idx_list <- sf::st_intersects(tracks, track_points) %>% 
  purrr::set_names(., nm = pull(tracks, name))

tracks_of_points <- lapply(track_point_idx_list, 
                           make_tracks_of_points, track_points = track_points)


my_tracks <- tracks_of_points %>% 
  keep(names(.) %like% my_site) %>% 
  map(points2line_trajectory)  ##convert our points to lines

# names(my_tracks)
# addPolylines_multi <- function(x){
#     addPolylines(data=x,  opacity=1, color = 'red',
#                    fillOpacity = 0.75, weight=2)
# }

#clean up workspace
rm(track_point_idx_list, tracks_of_points)
```

Map our stream, watershed and key points.

```{r map, echo=TRUE}
##--------lets map it-----------------------------------------------------------------------
map <- leaflet() %>%
  addTiles() %>%
  addProviderTiles("Esri.WorldImagery", group = "ESRI Aerial") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topo") %>%
  addPolylines(data=my_tracks$`125000_us_track1`,  opacity=1, color = 'red',
                   fillOpacity = 0.75, weight=2) %>%
  addPolylines(data=my_tracks$`125000_us_track1`,  opacity=1, color = 'blue',
               fillOpacity = 0.75, weight=2) %>%
  addLayersControl(
    baseGroups = c("Topo","ESRI Aerial"),
    overlayGroups = c(my_tracks$`125000_ds_track`),
    options = layersControlOptions(collapsed = T))
map
```


```{r echo=TRUE}

history <- drake_history(analyze = TRUE)
knitr::kable(
  head(history)
)
```

